### ISSUE TITLE
esy: "expected only version or source but both were provided"

### ISSUE THREAD

**Issue by jlwoodwa** [WasmCert/WasmCert-Coq#12]
When I run `esy` in the project directory as instructed, it returns the following error:
```
error: expected only version or source but both were provided
  reading package metadata from link-dev:./package.json
  loading root package metadata
esy: exiting due to errors above
```

**Comment by jlwoodwa** [comment]
It seems to work if all but the first `"version"` properties are deleted.

**Comment by raoxiaojia** [comment]
This is quite unexpected, since a commit targeting at fixing the dependencies (in particular, the duplicated version properties) should have been in place exactly around last week. 

Would it be possible if you could post the exact commit hash you are trying to build, so we could look into it and check as well?

**Comment by raoxiaojia** [comment]
Closing this thread due to inactivity. 

Summary of the response: it is likely that this issue is due to trying to build a different master branch, which is no longer maintained and should be archived. The current master branch was tested again, which compiled successfully in its current state.
