### ISSUE TITLE
bug in parser

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#16]
It seems that there is a bug somewhere in the binary parser.

I have a wasm file `foo.wasm` that I obtained from the WasmCert binary printer. 
It runs fine in nodejs but the interpreter from WasmCert fails with:
`wasm_interpreter: syntax error`

For the corresponding .wat file see [here](https://gist.github.com/womeier/20608ff4193c03ca0fe59ec7cfcae36b).

<br><br>
Setup to test the same thing:

The gist also includes a Coq file `foo_wasm.v` that contains the byte sequence of the same wasm file, obtained using this python script [here](https://github.com/womeier/certicoqwasm-testing/blob/master/wasm_to_coq.py). 

when compiling `foo_wasm.v` the parser returns None. (line 25, second file [here](https://gist.github.com/womeier/20608ff4193c03ca0fe59ec7cfcae36b))

**Comment by raoxiaojia** [comment]
Thanks for the report! The original issue is due to a mistake in the binary parser (which is unverified and very under-tested) in dealing with the `locals` field within the `code` section. The provided module is successfully parsed after the fix. In addition, further testing reveals some other minor issues on the pretty printer, which tries to convert integers to nat before printing them (oops). Both of these have been fixed in #17 . 

Please note that the current Coq formalisation uses a naive list memory representation, therefore allocating the memory with an initial size of 100 pages is not recommended (will likely cause it to crash) -- it is possible that we add another memory representation in the future, though. 

The module provided (after tweaks) is tested and can now be run correctly (`$main_function` returns `i32.const 36`), and the byte list can now be parsed in Coq as well.

**Comment by womeier** [comment]
I can confirm that it works now, thanks for solving it that quickly!

For testing, I added a roundtrip (printing to bytes and parsing) to the end of my compilation pipeline, and my benchmarks run through again. (I only use basic WebAssembly functionality, in any case I'm happy now.)

Thanks for the hint with the memory. That was a remainder, I don't actually need to run programs with that amount of memory.
