### ISSUE TITLE
small discrepancy from spec in pp

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#18]
a small thing I noticed when using the prettyprinter (pp.v)

when printing memory operations, the alignment is not printed correctly.

In pp.v, I believe it should look something like this:
`Definition pp_ao a o : string :=
  "offset=" ++ pp_immediate o ++ " align=" ++ (pp_immediate (2^a)).`

1)  the `offset=` and `align=` are required for the textformat, the order of the two matters.

2) In the textformat, it is not the exponent but 2^exponent for the alignment, see https://webassembly.github.io/spec/core/text/instructions.html#memory-instructions

actually, I'm not exactly sure about the a=2^n in the spec, you seem to be using `a` to represent the exponent. 
(not that it matters much, as the alignment doesn't have an impact on semantic behaviour)

With that fixed, the prettyprinter also produced runnable code for my example setup. (even if that was not the intended use)

**Comment by raoxiaojia** [comment]
Thanks for the comment! 

From the [spec](https://www.w3.org/TR/wasm-core-1/#memory-instructions⑦), it looks like the alignment argument provided in the instruction needs to be already the actual value (in a power of 2) instead of the exponent, which is currently parsed correctly (check the current [parser implementation](https://github.com/WasmCert/WasmCert-Coq/blob/c2422d3c6542e25123b14d0f72fac88359c4d1c8/theories/binary_format_parser.v#L191)), so there should be no extra taking of the exponential required in the semantics, or rendering to the text format.

I could be wrong though -- it is difficult to confirm this, since the alignment argument doesn't impact the semantic behaviour at all (it's merely a hint for hardware optimisations).

**Comment by raoxiaojia** [comment]
The part of the comment about needing the `offset=` and `align=` seems to be correct and needs to get a short fix.

**Comment by womeier** [comment]
foo.wat:

(module
  ;; function imports
  (memory 10)

  (func (export "test1")
    i32.const 0
    i32.load offset=0 align=5
  )
)

$ wat2wasm foo.wat
mem.wat:7:23: error: alignment must be power-of-two
    i32.load offset=0 align=5

**Comment by womeier** [comment]
It's possible I'm missing something, I don't understand the following:

wat file with `align=4`:
[mem.wat.txt](https://github.com/WasmCert/WasmCert-Coq/files/11236581/mem.wat.txt)

run `wat2wasm` on that file, obtain and parse the byte-sequence:
[mem_wasm.v.txt](https://github.com/WasmCert/WasmCert-Coq/files/11236585/mem_wasm.v.txt)

now, in the parsed module, the instruction has  `align=2`


The reason I care about this is that  `wat2wasm` complains, if align is not a power of 2.

**Comment by raoxiaojia** [comment]
I think you are right -- after some closer inspection, the `align` argument is represented differently in the text format, binary format, and the spec (formalism).

The specification defines the alignment to be the exponent only, which is also the correct encoding in the binary format. However, in the text format, the align argument is then supposed to be printed as the correct power of 2 instead of the exponent. So `align=2` in the spec and binary would correspond to `align=4` in the text format, as per the observation above.

Fortunately this means that the only thing needs to be fixed here is taking the power -- which means that the fix proposed in your original post is in fact about correct. This is now implemented in a standalone commit. 

Thanks a lot for chasing this down! Perhaps it would be an interesting side project to certify the binary parser and the pretty printer in some way as well.

**Comment by womeier** [comment]
Thanks!

That sounds interesting indeed. I might look into it in the summer, if time permits. (no guarantees)
