### ISSUE TITLE
bug in instantiation

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#25]
At instantiation, imported functions are not added to `store_record.(s_funcs)`,
which I expected to be the case from looking at e.g. the rule

```
 | r_invoke_host_diverge :
      forall a cl t1s t2s h ves vcs n m s f hs hs',
        List.nth_error s.(s_funcs) a = Some cl ->
        cl = FC_func_host (Tf t1s t2s) h ->
        ves = v_to_e_list vcs ->
        length vcs = n ->
        length t1s = n ->
        length t2s = m ->
        host_application hs s (Tf t1s t2s) h vcs hs' None ->
        reduce hs s f (ves ++ [::AI_invoke a]) hs' s f (ves ++ [::AI_invoke a])
```

Here is a small toy example that is close to what I need, see the comments in the file.

I'm not sure if I'm using `instantiate` as expected (in particular the `v_imps` and calling it with the empty store), see line 139.

It implies `False` when called with the empty store (see test_fn_call_false), which would seemingly not occur if the imported functions were added to the store and if the `List.Forall2 (external_typing s) v_imps t_imps /\` in `instantiate` was called with `s'` instead of `s`. 

[instantiation-test.v.txt](https://github.com/WasmCert/WasmCert-Coq/files/12479177/instantiation-test.v.txt)

thanks!

**Comment by raoxiaojia** [comment]
If modules are instantiated with some imports, then the imported entities need to *already* be in the store (since the imports are pointers to the store, in the end). Wasm import objects can potentially come from the instantiation results of previous modules; but in general, it is the obligation of the host (embedder) to provide any additional import objects which do not come from earlier module instantiations (e.g. host functions). So in short, the (host) functions to be imported by a module need to already exist in the store prior to instantiating the particular module.

The current Coq mechanisation is instantiated on a parametric host which does not provide any concrete host functions. `host.v` contains axiomatisation of a general host and an implementation of a dummy host which provides no host function. If a host with some known host functions are required, that can be done via implementing another Coq module instance of the host module type. However, this part is not tested very much beyond the dummy host (providing no host functions) and some experiments in the Iris branch (providing a concrete host language with some simple host operations, but removing the parametricity on the host, so it is slightly different and probably should not be looked into unless you're interested in the Iris logic part).

**Comment by raoxiaojia** [comment]
> 

In the example you included, note that the `instantiate` predicate is a relation stating the pre- and post-instantiation stores (to be precise, the post instantiation tuple also discusses about the exports and the start function, if defined) given a particular module code and a series of inputs. It isn't a guarantee that any module can be instantiated successfully with an arbitrary input. Indeed the `instantiate` relation cannot be satisfied in your example since the required import objects (`func 0` and `func 1`) do not exist in the store prior to instantiation (which is an empty store).

**Comment by womeier** [comment]
You're right, I actually don't even need to call the imported functions, just the function indices afterward need to be
correct.
So I'll just provide them before instantiation and this is not a bug then.

Thanks a lot for the fast reply!
