### ISSUE TITLE
table initialisation missing during instantiation

### ISSUE THREAD

**Issue by womeier** [WasmCert/WasmCert-Coq#42]
Active element segments should be copied to the table during instantiation.
It seems this was removed as part of the recent update to 2.0.

Was that intentional? (The same seems to be the case for active element segments initialising part of the memory, but I don't need that.)

### Sidenote
We'd like to keep a version that only uses Wasm 1.0 features and not yet e.g. `ref_call` instructions.
(Only using the 1.0 features with the current 2.0 WasmCert will produce binaries that one can run with a Wasm 1.0 engine, right?)

**Comment by raoxiaojia** [comment]
After the introduction of table ops in 2.0, table/memory initialisations are now in a separate stage at post-instantiation: instantiation now produces a config tuple (S; F; es) where es is an instruction stack that performs the correct table and memory initialisations (see point 14/15/16 and bottom of https://webassembly.github.io/spec/core/exec/modules.html#instantiation). So the store post-execution of these instructions is what you're looking for. IMO This tweak is quite helpful to cut away the lengthy definitions of manually initialising tables/memories, given that table operations are already part of the opsem.

This isn't possible for 1.0, at least not for tables since no instruction in the opsem allows manipulating tables -- if you want to stick strictly to 1.0+tail calls then I don't think this will work. 

However, the instantiation tweak only requires `memory.init`, `table.init`, `elem.drop` and `table.drop` instead of the full 2.0 opsem to be added to work -- in particular, you don't have to add instructions related to reference calls to implement this tweak. Maybe this is a feasible workaround?

**Comment by raoxiaojia** [comment]
> (Only using the 1.0 features with the current 2.0 WasmCert will produce binaries that one can run with a Wasm 1.0 engine, right?)

There might be a caveat at the printing of elems -- the conversion from AST to the binary format is not unique, and I used some 2.0 encodings in printing them. But it should be easy enough to replace that with the old definition. All the others should work.

**Comment by womeier** [comment]
thanks a lot, I missed that part of the instantiation.

I'll try the update to pretty print Wasm 1.0 binaries soon, thanks.
